# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/aharnish/dev/VR/sdl-streamer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/aharnish/dev/VR/sdl-streamer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aharnish/dev/VR/sdl-streamer/CMakeFiles /Users/aharnish/dev/VR/sdl-streamer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aharnish/dev/VR/sdl-streamer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DH2323SkeletonSDL2

# Build rule for target.
DH2323SkeletonSDL2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DH2323SkeletonSDL2
.PHONY : DH2323SkeletonSDL2

# fast build rule for target.
DH2323SkeletonSDL2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DH2323SkeletonSDL2.dir/build.make CMakeFiles/DH2323SkeletonSDL2.dir/build
.PHONY : DH2323SkeletonSDL2/fast

#=============================================================================
# Target rules for targets named VRStreamer

# Build rule for target.
VRStreamer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VRStreamer
.PHONY : VRStreamer

# fast build rule for target.
VRStreamer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VRStreamer.dir/build.make CMakeFiles/VRStreamer.dir/build
.PHONY : VRStreamer/fast

ExtendedSDL2Aux.o: ExtendedSDL2Aux.cpp.o
.PHONY : ExtendedSDL2Aux.o

# target to build an object file
ExtendedSDL2Aux.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VRStreamer.dir/build.make CMakeFiles/VRStreamer.dir/ExtendedSDL2Aux.cpp.o
.PHONY : ExtendedSDL2Aux.cpp.o

ExtendedSDL2Aux.i: ExtendedSDL2Aux.cpp.i
.PHONY : ExtendedSDL2Aux.i

# target to preprocess a source file
ExtendedSDL2Aux.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VRStreamer.dir/build.make CMakeFiles/VRStreamer.dir/ExtendedSDL2Aux.cpp.i
.PHONY : ExtendedSDL2Aux.cpp.i

ExtendedSDL2Aux.s: ExtendedSDL2Aux.cpp.s
.PHONY : ExtendedSDL2Aux.s

# target to generate assembly for a file
ExtendedSDL2Aux.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VRStreamer.dir/build.make CMakeFiles/VRStreamer.dir/ExtendedSDL2Aux.cpp.s
.PHONY : ExtendedSDL2Aux.cpp.s

SDL2Auxiliary/SDL2Auxiliary.o: SDL2Auxiliary/SDL2Auxiliary.cpp.o
.PHONY : SDL2Auxiliary/SDL2Auxiliary.o

# target to build an object file
SDL2Auxiliary/SDL2Auxiliary.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DH2323SkeletonSDL2.dir/build.make CMakeFiles/DH2323SkeletonSDL2.dir/SDL2Auxiliary/SDL2Auxiliary.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VRStreamer.dir/build.make CMakeFiles/VRStreamer.dir/SDL2Auxiliary/SDL2Auxiliary.cpp.o
.PHONY : SDL2Auxiliary/SDL2Auxiliary.cpp.o

SDL2Auxiliary/SDL2Auxiliary.i: SDL2Auxiliary/SDL2Auxiliary.cpp.i
.PHONY : SDL2Auxiliary/SDL2Auxiliary.i

# target to preprocess a source file
SDL2Auxiliary/SDL2Auxiliary.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DH2323SkeletonSDL2.dir/build.make CMakeFiles/DH2323SkeletonSDL2.dir/SDL2Auxiliary/SDL2Auxiliary.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VRStreamer.dir/build.make CMakeFiles/VRStreamer.dir/SDL2Auxiliary/SDL2Auxiliary.cpp.i
.PHONY : SDL2Auxiliary/SDL2Auxiliary.cpp.i

SDL2Auxiliary/SDL2Auxiliary.s: SDL2Auxiliary/SDL2Auxiliary.cpp.s
.PHONY : SDL2Auxiliary/SDL2Auxiliary.s

# target to generate assembly for a file
SDL2Auxiliary/SDL2Auxiliary.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DH2323SkeletonSDL2.dir/build.make CMakeFiles/DH2323SkeletonSDL2.dir/SDL2Auxiliary/SDL2Auxiliary.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VRStreamer.dir/build.make CMakeFiles/VRStreamer.dir/SDL2Auxiliary/SDL2Auxiliary.cpp.s
.PHONY : SDL2Auxiliary/SDL2Auxiliary.cpp.s

SkeletonSDL2.o: SkeletonSDL2.cpp.o
.PHONY : SkeletonSDL2.o

# target to build an object file
SkeletonSDL2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DH2323SkeletonSDL2.dir/build.make CMakeFiles/DH2323SkeletonSDL2.dir/SkeletonSDL2.cpp.o
.PHONY : SkeletonSDL2.cpp.o

SkeletonSDL2.i: SkeletonSDL2.cpp.i
.PHONY : SkeletonSDL2.i

# target to preprocess a source file
SkeletonSDL2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DH2323SkeletonSDL2.dir/build.make CMakeFiles/DH2323SkeletonSDL2.dir/SkeletonSDL2.cpp.i
.PHONY : SkeletonSDL2.cpp.i

SkeletonSDL2.s: SkeletonSDL2.cpp.s
.PHONY : SkeletonSDL2.s

# target to generate assembly for a file
SkeletonSDL2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DH2323SkeletonSDL2.dir/build.make CMakeFiles/DH2323SkeletonSDL2.dir/SkeletonSDL2.cpp.s
.PHONY : SkeletonSDL2.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VRStreamer.dir/build.make CMakeFiles/VRStreamer.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VRStreamer.dir/build.make CMakeFiles/VRStreamer.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VRStreamer.dir/build.make CMakeFiles/VRStreamer.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... DH2323SkeletonSDL2"
	@echo "... VRStreamer"
	@echo "... ExtendedSDL2Aux.o"
	@echo "... ExtendedSDL2Aux.i"
	@echo "... ExtendedSDL2Aux.s"
	@echo "... SDL2Auxiliary/SDL2Auxiliary.o"
	@echo "... SDL2Auxiliary/SDL2Auxiliary.i"
	@echo "... SDL2Auxiliary/SDL2Auxiliary.s"
	@echo "... SkeletonSDL2.o"
	@echo "... SkeletonSDL2.i"
	@echo "... SkeletonSDL2.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

